### ISSUE TITLE
pheonix 64 download page says ,"Reported Unwanted Software Page!" in mozila firefox

### ISSUE THREAD

**Issue by frndxyz** [ghostlander/Phoenixcoin-v0.6#3]

**Comment by ghostlander** [comment]
That's because of the bundled CPUminer most likely. It will be removed in the future releases.

**Comment by frndxyz** [comment]
however i have orbitcoin question, in UNOMP pool orbitcoin block is not accounted in redis , any fixed for windows wallet?

**Comment by ghostlander** [comment]
Issue resolved.
