### ISSUE TITLE
ubuntu 16 qt5

### ISSUE THREAD

**Issue by ghost** [ghostlander/Phoenixcoin-v0.6#5]
Who is interested to build it on Ubuntu 14 and up, on qt5, here is a patch.

    https://github.com/comarius/fragmente/blob/master/ubuntu16-qt5.patch

_it compiles from qtcreator and starts. Not yet tested in particular ...the Qurl.query() 
replacement._

**Comment by ghostlander** [comment]
Thanks. Qt5 should be supported soon.

**Comment by ghostlander** [comment]
3f224acab0df765e97ad643b35d2cd6b81d38f79
